require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Khatma' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'RNDownloadButton', :path => '../node_modules/react-native-download-button/ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  target 'KhatmaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Khatma-tvOS' do
  # Pods for Khatma-tvOS

  target 'Khatma-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
